config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  devise_for :users

  resources :trips do
    resources :locations

  end

  resources :locations do
    resources :addresses
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :location
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :trip
  has_many :addresses, dependent: :destroy
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :locations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
 has_many :trips, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_location
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  def index
    @addresses = @location.addresses
  end

  def show
  end

  def new
    @address = @location.addresses.new
  end

  def edit
  end

  def create
    @address = @location.addresses.new(address_params)

    if @address.save
      redirect_to [@location, @address]
    else
      render :new
    end
  end

  def update
    if @address.update(address_params)
      redirect_to [@location, @address]
    else
      render :edit
    end
  end

  def destroy
    @address.destroy
    redirect_to location_addresses_path
  end

  private

  def set_location
    @location = Location.find(params[:location_id])
  end

  def set_address
    @address = Address.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:name, :street, :city, :state, :zip)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:home, :about]

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_trip, only: [ :index, :new, :create]
  before_action :set_trip1, only: [:show, :edit, :update, :destroy]
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = @trip.locations.all
  end

  def show
  end

  def new
    @location = @trip.locations.new
  end

  def edit
  end

  def create
    @location = @trip.locations.new(location_params)
    if @location.save
      redirect_to 
    else
      render :new
    end
  end

  def update
    if @location.update(location_params)
      redirect_to [@trip, @location]
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to trip_locations_path(@trip)
  end

  private

  def set_trip
    @trip = Trip.find(params[:trip_id])
  end

  def set_trip1
    @trip1 = Trip.find(params[:id])
  end

  def set_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:name, :attraction, :rating, :note)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
  end

  def about
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  
  def index
    @trips = current_user.trips
  end

  def show
  end

  def new
    @trip = Trip.new
  end

  def edit
  end

  def create
    @trip = current_user.trips.new(trip_params)
    
    if @trip.save
      redirect_to trips_path
    else
      render :new
    end
  end

  def update
    if @trip.update(trip_params)
      redirect_to @trip
    else
      render :edit
    end
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end

  private
    def set_trip
      @trip = current_user.trips.find(params[:id])
    end

    def trip_params
      params.require(:trip).permit(:title, :people, :stops, :transportation)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: [@location, @address], local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name of Location", autofocus: true %>
    
    <%= f.label :street %>
    <%= f.text_field :street, required: true, placeholder: "Street Address", autofocus: true %>
  
    <%= f.label :city %>
    <%= f.text_field :city, required: true, placeholder: "City", autofocus: true %>
    
    <%= f.label :state %>
    <%= f.text_field :state, required: true, placeholder: "State", autofocus: true %>

    <%= f.label :zip %>
    <%= f.text_field :zip, required: true, placeholder: "Zip Code", autofocus: true %>

    <%= f.submit nil, class: "ui-button"%>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Edit Location</h1>

<%= render partial: "form", location: @address %>

app/views/addresses/index.html.erb
<h1 class="ui header centered">Address</h1>
<%= link_to 'New Address', new_location_address_path(@location)%>
<div class="ui divider"></div>
<h2>Welcome <%= current_user.first_name %></h2>
<br />
<div class="ui grid">
  <% @addresses.each do |address| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui card">
        <div class="image">
          <img src="https://picsum.photos/200/300"/>
        </div>
        <div class="content">
           <%= link_to " #{address.name}", location_address_path(@location, address), class: "ui header centered" %>
        </div>
        <div class="extra content">
           <div class="ui three buttons">
             <button class= "ui blue basic button"><%= link_to 'Edit Address', edit_location_address_path(@location, address) %></button>
              <div class= 'or'></div>
              <button class= "ui green basic button"><%= link_to 'View Address', location_address_path(@location, address) %></button>
              <div class= 'or'></div>
              <button class="ui red basic button"><%= link_to 'Destroy', location_address_path(@location, address), method: :delete, data: { confirm: 'Are you sure?' } %></button>
            </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render partial: "form", location: @address %>

app/views/addresses/show.html.erb
<h4>Name: <%= @address.name %></h4>
<h4>Street <%= @address.street %></h4>
<h4>City: <%= @address.city %></h4>
<h4>State: <%= @address.state%></h4>
<h4>Zip: <%= @address.zip%></h4>

<br />
<br />
<%= link_to 'Edit Address', edit_location_address_path([@location, @address]) %> |
<%= link_to 'Delete Address', [@location, @address], method: :delete %> |
<%= link_to 'Back To Location', trip_locations_path(@location) %>

app/views/layouts/_navbar.html.erb
<nav class="ui menu">
  <button class="ui button">
    <%= link_to "Trips", trips_path %>
  </button>
  <button class="ui button">
    <%= link_to "Add Trip", new_trip_path%>
  </button>
  <div class="right menu">
   <% if current_user %>
    <button class="ui button">
      <%= link_to "Logout", destroy_user_session_path, method: :delete%>
    </button>
   <% else %>
    <button class="ui button">
     <%= link_to "Register", new_user_registration_path%>
    </button>
    <button class="ui button">
     <%= link_to "Login", new_user_session_path%>
    </button>
   <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <%= render partial: "layouts/navbar" %>
  <div class="ui container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: [@trip, @location], local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name of Location", autofocus: true %>
    
    <%= f.label :attraction %>
    <%= f.text_field :attraction, required: true, placeholder: "What to do?", autofocus: true %>
   
    <%= f.label :rating %>
    <%= f.text_field :rating, required: true, placeholder: "Rate this", autofocus: true %>
    
    <%= f.label :note %>
    <%= f.text_field :note, required: true, placeholder: "Tell me about it", autofocus: true %>
    <%= f.submit nil, class: "ui-button"%>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>New Location</h1>

<%= render partial: "form", location: @location %>

app/views/locations/index.html.erb
<h1 class="ui header centered">Locations</h1>
<%= link_to 'New location', new_trip_location_path(@trip)%>
<div class="ui divider"></div>
<h2>Welcome <%= current_user.first_name %></h2>
<br />
<div class="ui grid">
  <% @locations.each do |location| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui card">
        <div class="image">
          <img src="https://picsum.photos/200/300"/>
        </div>
        <div class="content">
           <%= link_to " #{location.name}", trip_location_path(@trip, location), class: "ui header centered" %>
        </div>
        <div class="extra content">
           <div class="ui three buttons">
             <button class= "ui blue basic button"><%= link_to 'Edit', edit_trip_location_path(@trip, location) %></button>
              <div class= 'or'></div>
              <button class= "ui green basic button"><%= link_to 'View Address', location_addresses_path(location) %></button>
              <div class= 'or'></div>
              <button class="ui red basic button"><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></button>
            </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render partial: "form", location: @location %>

<%# link_to "Back", @location%>

app/views/locations/show.html.erb
<h4>Name: <%= @location.name %></h4>
<h4>Attraction: <%= @location.attraction %></h4>
<h4>Rating: <%= @location.rating %></h4>
<h4>Note: <%= @location.note%></h4>

<br />
<br />
<%= link_to 'Edit Location', edit_trip_location_path([@trip, @location]) %> |
<%= link_to 'Delete Location', [@trip, @location], method: :delete %> |
<%= link_to 'View Address', location_addresses_path(@location, @address)%> |
<%= link_to 'Back To Locations', trip_locations_path(@trip1, @location) %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<div class="ui container">
  <div class"ui very padded segement">
    <img class="ui centered massive image", src="https://images.haarets.co.il/image/fetch/w_609,h_343,q_auto,c_fill,f_auto/fl_any_format.preserve_transparency.progressive:none/https://www.haaretz.com/polopoly_fs/1.5633863.1515366789!/image/1018316866.jpg" />
  </div>
    <div class="ui containter" id="closed_gates">
      <h1 class="ui center aligned header red">Oh No!  You need to log in to see our TRIPS FROM HELL</h1>
      <p class="ui center aligned header red">Sign up, or log in, to meet your maker!</p>
    </div>
</div>

app/views/trips/_form.hmtl.erb
<%= form_with(model: trip, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, required: true, placeholder: "Name of Trip", autofocus: true %>
    
    <%= f.label :people %>
    <%= f.text_field :people, required: true, placeholder: "How Many People", autofocus: true %>
   
    <%= f.label :stops %>
    <%= f.text_field :stops required: true, placeholder: "Stops", autofocus: true %>
    
    <%= f.label :transportation %>
    <%= f.text_field :transportation, required: true, placeholder: "Transportation Type", autofocus: true %>
    <%= f.submit nil, class: "ui-button"%>
  </div>
<% end %>
  

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, required: true, placeholder: "Name of Trip", autofocus: true %>
    
    <%= f.label :people %>
    <%= f.text_field :people, required: true, placeholder: "How Many People", autofocus: true %>
   
    <%= f.label :stops %>
    <%= f.text_field :stops, required: true, placeholder: "Stops", autofocus: true %>
    
    <%= f.label :transportation %>
    <%= f.text_field :transportation, required: true, placeholder: "Transportation Type", autofocus: true %>
    <%= f.submit nil, class: "ui-button"%>
  </div>
<% end %>
  

app/views/trips/edit.html.erb
<h1 class= "ui header centered">Edit Trip</h1>
<hr />
<%= render "form", trip: @trip %>
<br>
<button type="button" class="btn btn-outline-primary btn-sm">
<%= link_to "show", trip_path(@trip) %>
</button>
<button type="button" class="btn btn-outline-primary btn-sm">
<%= link_to "Back", trips_path %>
</button>

app/views/trips/index.html.erb
<h1 class="ui header centered">Trips</h1>
<div class="ui divider"></div>
<h2>Welcome <%= current_user.first_name %></h2>
<br />
<div class="ui grid">
  <% @trips.each do |trip| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui card">
        <div class="image">
          <img src="https://picsum.photos/200"/>
        </div>
        <div class="content">
           <%= link_to "#{trip.title}", trip_path(trip), class: " ui header centered" %>
        </div>
        <div class="extra content">
           <div class="ui three buttons">
             <button class= "ui blue basic button"><%= link_to 'Edit', edit_trip_path(trip) %></button>
              <div class= 'or'></div>
              <button class= "ui green basic button"><%= link_to 'View Locations', trip_locations_path(trip) %></button>
              <div class= 'or'></div>
              <button class="ui red basic button"><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></button>
            </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render "form", trip: @trip %>

<%= link_to "Back", @trip%>

app/views/trips/show.html.erb
<div class="ui centered card">
  <div class="image">
     <img src="https://picsum.photos/200"/>
    </div>
    <div class="content">
      <p class="header">
      <%= @trip.title %> 
    </p>
</div>
</div>
<hr />
<br />

<div class= "ui centered grid">
  <% @trip.locations.each do |location| %>
   <ol class="ui list">
    <div class="four wide column">
     <li> <%= link_to "#{location.name}", trip_location_path(@trip, location) %> <%= location.attraction %>  </li></div>
     </ol>
   </div>
  <%end%>
</div>
<br />
<br />
<div class="ui buttons">


<button class= "ui positive basic button"><%= link_to 'Add location', new_trip_location_path(@trip) %></button>

</div>
<button class= "ui green right floated basic button"><%= link_to 'Back', trips_path %></button>